name: build docs

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-html:
    name: build html 
    runs-on: ubuntu-latest 
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags.
      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci/requirements/docs.yml
          create-args: >-
            python=3.10
      - name: Version info
        run: |
          conda info -a
          conda list
      - name: build html 
        run: |
          #python -m sphinx -T -E -b html -d _build/doctrees -D language=en docs html
          sphinx-build docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true


